{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spring-boot-helm-demo.serviceAccountName" . }}
  labels:
{{ include "spring-boot-helm-demo.labels" . | indent 4 }}
{{- end -}}
